export const APP_STATE_LOADING = 'APP_STATE_LOADING';
export const APP_STATE_ERROR = 'APP_STATE_ERROR';
export const APP_STATE_READY = 'APP_STATE_READY';
export const APP_HAS_LOCATION = 'APP_HAS_LOCATION';
export const APP_NO_LOCATION = 'APP_NO_LOCATION';
