export const VEHICLES_LOADING = 'VEHICLES_LOADING';
export const VEHICLES_LOAD_ERROR = 'VEHICLES_LOAD_ERROR';
export const VEHICLES_LOADED = 'VEHICLES_LOADED';
export const VEHICLE_STOPS_LOADING = 'VEHICLE_STOPS_LOADING';
export const VEHICLE_STOPS_LOAD_ERROR = 'VEHICLE_STOPS_LOAD_ERROR';
export const VEHICLE_STOPS_LOADED = 'VEHICLE_STOPS_LOADED';
